# Generated by Django 4.2.30 on 2026-06-11 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_seed_default_shop"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="size",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="product",
            name="unit",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AddField(
            model_name="shop",
            name="complete_address",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="shop",
            name="owner_name",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="shop",
            name="phone_number",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AddField(
            model_name="shop",
            name="shop_type",
            field=models.CharField(
                choices=[
                    ("grocery", "Grocery"),
                    ("cloths", "Cloths"),
                    ("electronics", "Electronics"),
                ],
                default="electronics",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="shop",
            name="address",
            field=models.CharField(blank=True, default="", max_length=400),
        ),
    ]
